### ISSUE TITLE
Settings automation

### ISSUE THREAD

**Issue by Revadike** [A2TC-YT/afk-class-item-double-chest#1]
Why not do this?
if Destiny is not running: 
1) backup cvars.xml
2) edit cvars to set all correct settings
3) launch game
4) run automation script
5) if destiny stops running, or on script exit, restore cvars.xml

if Destiny is already running, just do step 4.

**Comment by A2TC-YT** [comment]
most of the important settings to change cant be changed in cvars (video settings) and some of them (mainly screen bounds) would mess with any menuing an automated settings thing would do

**Comment by Revadike** [comment]
> most of the important settings to change cant be changed in cvars (video settings) and some of them (mainly screen bounds) would mess with any menuing an automated settings thing would do

I imagine screen bounds is max for 99% of people. What other settings are you missing? Its a lot of settings you need to match, so any help is already really nice.
