### ISSUE TITLE
Brightness issues, doesn't detect chest load-in.

### ISSUE THREAD

**Issue by davelens** [A2TC-YT/afk-class-item-double-chest#10]
### Context
* I'm on Windows 11. Night light and HDR are off
* I have an ASUS monitor, default profile (`ASUS VG27A color profile, D6500`)
* Not running Flux or any blue light filters
* Not using any overlays, as far as I'm aware. I disabled the Steam overlay
* I have a 4080 super, but not running Geforce Experience. Nvidia HDR is off
* I"ve copied all Destiny settings, triple checked them; they're the same as advertised
* My Destiny window is centered, windowed, 1280x720

### The issue
First it seemed to miss the landing zone selection in orbit, which I was able to correct by changing `orbit_landing()`'s every occurrence of `270` into `330`. In the `; we missed the landing zone` block the click was changed from `253` to `353` and `255` to `355`.

When the large green Launch button for the landing comes up, it still appears stuck trying to select the Landing node. Which seems to indicate it does not pass the `percent_white >= 0.4` check. I'll reiterate that my brightness is set to `7`.

I tried running this:
```
percent_white := simpleColorCheck("33|573|24|24", 24, 24)
MsgBox, % "Your percent_white value is " percent_white "."
```
And the output is always `0.0000000`. So my guess would be something's up with the `simpleColorCheck` function, but I'm not savvy enough with AHK to debug it properly.

I tried removing the second check entirely, which succesfully clicked the green Launch button. However, once I'm in the Landing, it doesn't seem to detect chest load-in.

So from what I can gather from issues other people have had, it seems to be a brightness issue.

Any suggestions or ideas how I can proceed?

Many thanks if you made it through to here.

**Comment by Zenairo** [comment]
https://thrallway.com Join the discord and ping me.

**Comment by Zenairo** [comment]
Issue was screen bounds had not been set to maximum.
