### ISSUE TITLE
I have run the macro for about 30 mins now.

### ISSUE THREAD

**Issue by iCxbra** [A2TC-YT/afk-class-item-double-chest#15]
I have run it for about 30 mins and it loads into the Pale Heart, waits and searches for the chests then reloads back into the pale heart. 

Edit*-I have tried to use it again today and now it just loads me into the landing then the overlay says it didnt detect spawn in.

**Comment by iCxbra** [comment]
For clarification on the overlay it never gets past waiting for chest spawns.

**Comment by paintbeat** [comment]
I am also having issues with it detecting my character loading in. Same error: "Didn't Detect Spawn in :("
Double checked video settings. Possible adjust to script to shorten time to load section? I am wondering if I am loading "too fast" for macro.

Edit: After looking a bit at code, just looks like a loop, please disregard my last sentence about load times. 
Follow-up question: What is the macro looking for for a load in?

**Comment by t1m0shi** [comment]
Also getting "didnt detect spawn in" error

**Comment by Reynbow** [comment]
Yeah, various issues here with version 2 also. Going to have to go back to using the previous version I have downloaded. Seems version 2 is completely broken.

**Comment by A2TC-YT** [comment]
sorry to hear you guys are having issues with it, there are plenty of people running it just fine, please join the discord if you need help setting it up
https://discord.gg/KGyjysA5WY

**Comment by Reynbow** [comment]
I can't imagine it's a setup issue if version 2 breaks within minutes of it running, but the previous version runs all night without issue.

**Comment by t1m0shi** [comment]
I was able to get it working. For some reason my brightness went back to 5, but after I changed back to 7 and double checked the other settings, it was smooth sailing.
