### ISSUE TITLE
Fixed Landing not being launched 

### ISSUE THREAD

**Issue by wmy3044** [A2TC-YT/afk-class-item-double-chest#16]
reload_landing() ; in the name innit
{
    loop, 5
    {   
        Send, % "{" key_binds["ui_open_director"] "}"
        Sleep, 1000 
        d2_click(20, 360, 0) ;different
        Sleep,840 
        d2_click(256, 360, 0) ;different
        Sleep, 100 
        PixelSearch, Px, Py, DESTINY_X+256, DESTINY_Y+350, DESTINY_X+640, DESTINY_Y+350, 0xFFFFFF, 0, Fast RGB ;different
        d2_click(Px-DESTINY_X, 340) ;different
        Sleep, 134
        Send, {LButton Down}
        Sleep, 1100
        Send, {LButton Up}
        Sleep, 1000
        ; check if we are still on the map screen (this means this function fucked up)
        percent_white := exact_color_check("974|703|4|3", 4, 3, 0xBBBBBB)
            if (!percent_white >= 0.3) ; we clicked succesfully
                break
            Send, % "{" key_binds["ui_open_director"] "}"
            Sleep, 2000
            continue ; 
        break
    }
    return
}
orbit_landing() ; loads into the landing from orbit
{
    loop, 5
    {
        Send, % "{" key_binds["ui_open_director"] "}"
        Sleep, 1000
        d2_click(640, 360, 0)
        Sleep, 500
        d2_click(640, 360)
        Sleep, 1000
        d2_click(20, 360, 0);different
        Sleep,850
        d2_click(256, 360, 0);different
        Sleep, 100 
        PixelSearch, Px, Py, DESTINY_X+256, DESTINY_Y+350, DESTINY_X+640, DESTINY_Y+350, 0xFFFFFF, 0, Fast RGB ;different
        d2_click(Px-DESTINY_X, 340) ;different
        Sleep, 134
        Send, {LButton Down}
        Sleep, 100
        Send, {LButton Up}
        Sleep, 1300
        percent_white := simpleColorCheck("33|573|24|24", 24, 24)
        if (!percent_white >= 0.4) ; we missed the landing zone
        {
          Send, % "{" key_binds["ui_open_director"] "}"
          Sleep, 1500
          Continue
        }
        d2_click(1080, 601, 0)
        Sleep, 100
        d2_click(1080, 601)
        return true
    }
    return false ; 5 fuckups in a row and it fails
}

**Comment by hkfires** [comment]
This is the most effective solution I have ever seen.

**Comment by wmy3044** [comment]
1.4
reload_landing() ; in the name innit
{
    loop, 5
    {   
        Send, % "{" key_binds["ui_open_director"] "}"
        Sleep, 1000 
        d2_click(20, 360, 0)
        Sleep,840 
        d2_click(256, 360, 0)
        Sleep, 100 
        PixelSearch, Px, Py, DESTINY_X+256, DESTINY_Y+350, DESTINY_X+640, DESTINY_Y+350, 0xFFFFFF, 0, Fast RGB
        if (!Px > 0)
            {
                Send, % "{" key_binds["ui_open_director"] "}"
                Sleep, 2000
                Continue
            }
        d2_click(Px-DESTINY_X, 340)
        Sleep, 134 
        Send, {LButton Down}
        Sleep, 1100
        Send, {LButton Up}
        Sleep, 1000
        percent_white := exact_color_check("920|58|56|7", 56, 7, 0xECECEC)
        if (percent_white >= 0.3)
            {
                Send, % "{" key_binds["ui_open_director"] "}"
                Sleep, 2000
                Continue
            }
        return true
    }
    return false
}

orbit_landing() ; loads into the landing from orbit
{
    loop, 5
    {
        Send, % "{" key_binds["ui_open_director"] "}"
        Sleep, 1000 ;
        d2_click(640, 360, 0)
        Sleep, 500
        d2_click(640, 360)
        Sleep, 1500
        d2_click(20, 360, 0)
        Sleep,850
        d2_click(256, 360, 0)
        Sleep, 100 
        PixelSearch, Px, Py, DESTINY_X+256, DESTINY_Y+350, DESTINY_X+640, DESTINY_Y+350, 0xFFFFFF, 0, Fast RGB
        if (!Px > 0)
            {
                Send, % "{" key_binds["ui_open_director"] "}"
                Sleep, 1500
                Continue
            }
        d2_click(Px-DESTINY_X, 340)
        Sleep, 134 
        Send, {LButton Down}
        Sleep, 100
        Send, {LButton Up}
        Sleep, 1300
        percent_white := simpleColorCheck("33|573|24|24", 24, 24) ; check again, if still not in the right screen, close map and try again
        if (!percent_white >= 0.4)
            {
                Send, % "{" key_binds["ui_open_director"] "}"
                Sleep, 1500
                Continue
            }
        d2_click(1080, 601, 0)
        Sleep, 100
        d2_click(1080, 601)
        return true
    }
    return false ; 5 fuckups in a row and it fails
}

**Comment by wmy3044** [comment]
> This is the most effective solution I have ever seen.
fix some bug ...

**Comment by AlexBeauregard18** [comment]
Landing is now being selected but Launch screen just repeats 5 times and goes back to character selection,
