### ISSUE TITLE
Landing not launching 

### ISSUE THREAD

**Issue by AlexBeauregard18** [A2TC-YT/afk-class-item-double-chest#17]
I copied the text from another patch note concerning the landing not being selected, 5 attempts and back to character selection.
Now landing is being selected, but once on the launch screen, it still attempts to choose the landing instead of launching. 
5 selections without any attempts of launching and back to character selection. 

https://github.com/user-attachments/assets/8c8435f0-3a8e-4954-885c-dc9fcf39108a

**Comment by A2TC-YT** [comment]
please join the discord and use the support channel for help
https://discord.gg/KGyjysA5WY
