### ISSUE TITLE
Stats API

### ISSUE THREAD

**Issue by Makeshift** [A2TC-YT/afk-class-item-double-chest#22]
Hey,

Really good job on this script! 

I noticed you added a "heartbeat" that sends some stats to an API. Would be really interested in seeing some of this crowdsourced data to see if we can work out what limitations exist under the hood, eg if there's a minimum time between drops and such. I know it's pretty early for that, but it's a cool idea.

Are you planning on making that data available at all?

I would have asked on discord, but I couldn't find a way to reply to any of the messages in your channel.

Cheers

**Comment by Makeshift** [comment]
`!scriptStats` in the macros discord. Thanks!

**Comment by Zenairo** [comment]
Stats can be requested in our discord with !scriptStats command. DM me on discord if you want more info about the API.
