### ISSUE TITLE
Issue with Warlock's Burst Glide on Box 20

### ISSUE THREAD

**Issue by Cherryu1** [A2TC-YT/afk-class-item-double-chest#5]
First of all, thank you for creating and sharing this script, it's been really helpful!

I'm having trouble with the Warlock's script for the 20 boxes. After collecting Box 21, I'm unable to use Burst Glide to jump from the ground near Box 21 to the platform of Box 20.

Steps to Reproduce

1. Detect Box 21 and Box 20.
2. Collect Box 21.
3. Try to jump to Box 20 using Burst Glide from the ground near Box 21.

What Happens

The Warlock can't make the jump.

Expected

The Warlock should be able to jump to Box 20 using Burst Glide.

Thanks again for your hard work on this script!

**Comment by Scetick** [comment]
I also encountered the same problem

**Comment by A2TC-YT** [comment]
this was an issue with the very initial release of 1.2 where it was doing the titan inputs for warlock jumps, this has been fixed in recent versions
